### ISSUE TITLE
Installation via bower?

### ISSUE THREAD

**Issue by binarykitchen** [ractivejs/rv#3]
Would be great if this could be installed via bower ...

**Comment by Rich-Harris** [comment]
Sorry, I totally missed this before. Have added a bower.json file, but I just tried `bower install requirejs-ractive` and it failed on me. Any ideas?

**Comment by binarykitchen** [comment]
Mhhh, it is in the search results:

``` bash
$ bower search ractive
Search results:

    ractive git://github.com/Rich-Harris/Ractive
    requirejs-ractive git://github.com/Rich-Harris/require-ractive-plugin.git
    codemirror-interactive-numbers git://github.com/fullstackio/codemirror-interactive-numbers.git
    backbone.ractive git://github.com/MinnPost/backbone.ractive.git
```

but I failed to install too (verbose mode on):

``` bash
$ bower install requirejs-ractive -V
bower requirejs-ractive#*   not-cached git://github.com/Rich-Harris/require-ractive-plugin.git#*
bower requirejs-ractive#*      resolve git://github.com/Rich-Harris/require-ractive-plugin.git#*
bower requirejs-ractive#*     download https://github.com/Rich-Harris/require-ractive-plugin/archive/v0.1.3.tar.gz
bower requirejs-ractive#*      extract archive.tar.gz
bower requirejs-ractive#*     resolved git://github.com/Rich-Harris/require-ractive-plugin.git#0.1.3
bower requirejs-ractive#*        error Object #<Object> has no method 'trim'

Stack trace:
TypeError: Object #<Object> has no method 'trim'
    at trim (/usr/local/share/npm/lib/node_modules/bower/node_modules/bower-endpoint-parser/index.js:106:22)
    at Object.json2decomposed (/usr/local/share/npm/lib/node_modules/bower/node_modules/bower-endpoint-parser/index.js:48:13)
    at Manager.<anonymous> (/usr/local/share/npm/lib/node_modules/bower/lib/core/Manager.js:378:47)
    at /usr/local/share/npm/lib/node_modules/bower/node_modules/mout/object/forOwn.js:12:27
    at exec (/usr/local/share/npm/lib/node_modules/bower/node_modules/mout/object/forIn.js:57:19)
    at forIn (/usr/local/share/npm/lib/node_modules/bower/node_modules/mout/object/forIn.js:38:17)
    at Object.forOwn (/usr/local/share/npm/lib/node_modules/bower/node_modules/mout/object/forOwn.js:10:9)
    at Manager._parseDependencies (/usr/local/share/npm/lib/node_modules/bower/lib/core/Manager.js:374:17)
    at Manager._onFetchSuccess (/usr/local/share/npm/lib/node_modules/bower/lib/core/Manager.js:293:10)
    at /usr/local/share/npm/lib/node_modules/bower/node_modules/q/q.js:1186:26

Console trace:
Trace
    at StandardRenderer.error (/usr/local/share/npm/lib/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.updateNotifier.packageName (/usr/local/share/npm/lib/node_modules/bower/bin/bower:109:18)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/usr/local/share/npm/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/share/npm/lib/node_modules/bower/lib/commands/install.js:27:16
    at _rejected (/usr/local/share/npm/lib/node_modules/bower/node_modules/q/q.js:808:24)
    at /usr/local/share/npm/lib/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/usr/local/share/npm/lib/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/usr/local/share/npm/lib/node_modules/bower/node_modules/q/q.js:752:41)
    at /usr/local/share/npm/lib/node_modules/bower/node_modules/q/q.js:574:44

System info:
Bower version: 1.2.7
Node version: 0.10.21
OS: Darwin 13.0.0 x64
```

**Comment by binarykitchen** [comment]
Alright, I reported it ...

**Comment by binarykitchen** [comment]
Here is the answer:
https://github.com/bower/endpoint-parser/issues/6#issuecomment-27167054

Make the dependencies an object ...

**Comment by Rich-Harris** [comment]
D'oh! Good sleuthing, many thanks. Have fixed bower.json and replaced the tag, so it works now.

**Comment by alexserver** [comment]
now we need the package to appear in official search results, for the souls that might have lose the path http://bower.io/search/?q=requirejs-ractive

**Comment by Rich-Harris** [comment]
It should now be `rv` rather than `requirejs-ractive` - I've just registered it with bower and `bower install rv` now works.

It won't show up in bower search, because they apparently show every package that includes the search string anywhere (e.g. in README files), without checking it's not just a sequence of characters in the middle of a word, then showing all results in order of Github stars. Which is just the kind of monumental idiocy that I've come to expect from bower

**Comment by wenerme** [comment]
bower install rv also need ractive, so still need to install requirejs-ractive ?

**Comment by Rich-Harris** [comment]
@wenerme no, requirejs-ractive is deprecated - easiest thing is to install `rv` and `ractive` together with `bower i rv ractive`
